# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ratio_service_pb2 as ratio__service__pb2


class CurrencyInfoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRatio = channel.unary_unary(
        '/exchange_rate.CurrencyInfo/GetRatio',
        request_serializer=ratio__service__pb2.WantedCurrencies.SerializeToString,
        response_deserializer=ratio__service__pb2.CurrenciesRatio.FromString,
        )
    self.UpdateRatio = channel.unary_stream(
        '/exchange_rate.CurrencyInfo/UpdateRatio',
        request_serializer=ratio__service__pb2.WantedCurrencies.SerializeToString,
        response_deserializer=ratio__service__pb2.Ratio.FromString,
        )


class CurrencyInfoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetRatio(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateRatio(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CurrencyInfoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRatio': grpc.unary_unary_rpc_method_handler(
          servicer.GetRatio,
          request_deserializer=ratio__service__pb2.WantedCurrencies.FromString,
          response_serializer=ratio__service__pb2.CurrenciesRatio.SerializeToString,
      ),
      'UpdateRatio': grpc.unary_stream_rpc_method_handler(
          servicer.UpdateRatio,
          request_deserializer=ratio__service__pb2.WantedCurrencies.FromString,
          response_serializer=ratio__service__pb2.Ratio.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'exchange_rate.CurrencyInfo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
