# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratio_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ratio_service.proto',
  package='exchange_rate',
  syntax='proto3',
  serialized_pb=_b('\n\x13ratio_service.proto\x12\rexchange_rate\"?\n\x10WantedCurrencies\x12\x13\n\x0b\x62\x61seCurCode\x18\x01 \x01(\t\x12\x16\n\x0ewantedCurCodes\x18\x02 \x03(\t\"9\n\x05Ratio\x12\x0f\n\x07\x62\x61seCur\x18\x01 \x01(\t\x12\x10\n\x08otherCur\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\"6\n\x0f\x43urrenciesRatio\x12#\n\x05ratio\x18\x01 \x03(\x0b\x32\x14.exchange_rate.Ratio2\xa3\x01\n\x0c\x43urrencyInfo\x12K\n\x08GetRatio\x12\x1f.exchange_rate.WantedCurrencies\x1a\x1e.exchange_rate.CurrenciesRatio\x12\x46\n\x0bUpdateRatio\x12\x1f.exchange_rate.WantedCurrencies\x1a\x14.exchange_rate.Ratio0\x01\x62\x06proto3')
)




_WANTEDCURRENCIES = _descriptor.Descriptor(
  name='WantedCurrencies',
  full_name='exchange_rate.WantedCurrencies',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseCurCode', full_name='exchange_rate.WantedCurrencies.baseCurCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wantedCurCodes', full_name='exchange_rate.WantedCurrencies.wantedCurCodes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=101,
)


_RATIO = _descriptor.Descriptor(
  name='Ratio',
  full_name='exchange_rate.Ratio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseCur', full_name='exchange_rate.Ratio.baseCur', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='otherCur', full_name='exchange_rate.Ratio.otherCur', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='exchange_rate.Ratio.value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=160,
)


_CURRENCIESRATIO = _descriptor.Descriptor(
  name='CurrenciesRatio',
  full_name='exchange_rate.CurrenciesRatio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ratio', full_name='exchange_rate.CurrenciesRatio.ratio', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=216,
)

_CURRENCIESRATIO.fields_by_name['ratio'].message_type = _RATIO
DESCRIPTOR.message_types_by_name['WantedCurrencies'] = _WANTEDCURRENCIES
DESCRIPTOR.message_types_by_name['Ratio'] = _RATIO
DESCRIPTOR.message_types_by_name['CurrenciesRatio'] = _CURRENCIESRATIO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WantedCurrencies = _reflection.GeneratedProtocolMessageType('WantedCurrencies', (_message.Message,), dict(
  DESCRIPTOR = _WANTEDCURRENCIES,
  __module__ = 'ratio_service_pb2'
  # @@protoc_insertion_point(class_scope:exchange_rate.WantedCurrencies)
  ))
_sym_db.RegisterMessage(WantedCurrencies)

Ratio = _reflection.GeneratedProtocolMessageType('Ratio', (_message.Message,), dict(
  DESCRIPTOR = _RATIO,
  __module__ = 'ratio_service_pb2'
  # @@protoc_insertion_point(class_scope:exchange_rate.Ratio)
  ))
_sym_db.RegisterMessage(Ratio)

CurrenciesRatio = _reflection.GeneratedProtocolMessageType('CurrenciesRatio', (_message.Message,), dict(
  DESCRIPTOR = _CURRENCIESRATIO,
  __module__ = 'ratio_service_pb2'
  # @@protoc_insertion_point(class_scope:exchange_rate.CurrenciesRatio)
  ))
_sym_db.RegisterMessage(CurrenciesRatio)



_CURRENCYINFO = _descriptor.ServiceDescriptor(
  name='CurrencyInfo',
  full_name='exchange_rate.CurrencyInfo',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=219,
  serialized_end=382,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRatio',
    full_name='exchange_rate.CurrencyInfo.GetRatio',
    index=0,
    containing_service=None,
    input_type=_WANTEDCURRENCIES,
    output_type=_CURRENCIESRATIO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateRatio',
    full_name='exchange_rate.CurrencyInfo.UpdateRatio',
    index=1,
    containing_service=None,
    input_type=_WANTEDCURRENCIES,
    output_type=_RATIO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENCYINFO)

DESCRIPTOR.services_by_name['CurrencyInfo'] = _CURRENCYINFO

# @@protoc_insertion_point(module_scope)
